djnagocrm/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from sales.views import 홈페이지

urlpatterns = [
    path('', 홈페이지),
    path('admin/', admin.site.urls),
    path('세일목록/', include('sales.urls', namespace='홈페이지') ),
]

sales/urls.py
from django.urls.conf import path
from .views import 세일_지우기, 세일_업데이트, 세일_입력, 세일목록, 세일상세

app_name = '세일목록1' # namespace과 이름 지정이 달라도 상관 없음

urlpatterns = [
    path('', 세일목록, name='목록'),
    path('<int:pk>/', 세일상세, name='상세'),
    path('make/', 세일_입력, name='생성'),
    path('<int:pk>/update/', 세일_업데이트, name='업뎃'),
    path('<int:pk>/delete/', 세일_지우기, name='지우기'),
]

sales/models.py
from django.db import models
# from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser

# Create your models here.

# 아이디 = get_user_model()

class 아이디(AbstractUser):
	pass
	# nickname = models.CharField(max_length=15)

class Sale(models.Model):
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=30)
	age = models.IntegerField(default=0)
	person = models.ForeignKey("Person", on_delete=models.CASCADE)
	# person = models.ForeignKey("Person", on_delete=models.SET_NULL, null=True)
	# person = models.ForeignKey("Person", on_delete=models.SET_DEFAULT, null=True, default=...)
	def __str__(self):
		return f"이름 : {self.last_name}{self.first_name}"

class Person(models.Model):
	회원 = models.OneToOneField(아이디, on_delete=models.CASCADE)
	# first_name = models.CharField(max_length=30)
	# last_name = models.CharField(max_length=30)
	def __str__(self):
		# return self.회원.email
		return self.회원.username

#----------------------------------------------------------

# from django.db import models
# from django.contrib.auth.models import AbstractUser

# class 아이디(AbstractUser):
# 	pass

# class Sale(models.Model):
# 	first_name = models.CharField(max_length=30)
# 	last_name = models.CharField(max_length=30)
# 	age = models.IntegerField(default=0)
# 	person = models.ForeignKey(아이디, on_delete=models.CASCADE)

sales/forms.py
from django import forms
from django.forms import fields
from sales.models import Sale

class SaleModelForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = ('first_name', 'last_name', 'age', 'person')
 
class SalesForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)

sales/views.py
from django.db import models
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import CreateView, DeleteView
from django.urls import reverse_lazy
from sales.forms import SalesForm, SaleModelForm
from sales.models import Person, Sale, 아이디

# Create your views here.


def 세일목록(request):
    사람 = Sale.objects.all()
    context = {'사람키': 사람,
               #    '사람first':사람.first,
               }
    return render(request, "newfolder/세일목록.html", context)


def 세일상세(request, pk):
    # print(pk)
    # print(세일)
    # return HttpResponse(pk+" : 여기 상세 정보입니다")
    사람 = Sale.objects.get(id=pk)
    context = {'사람키': 사람,
               }
    return render(request, "newfolder/세일상세.html", context)

def 세일_입력(request):  # 기초부터 제작하는 장고, ModelForm
    print(request.POST)  # 객체
    폼 = SaleModelForm()
    if request.method == "POST":
        폼 = SaleModelForm(request.POST)
        if 폼.is_valid():
            폼.save()
            return redirect("/세일목록")
    context = {
        "폼키": 폼
    }
    return render(request, "newfolder/세일_입력.html", context)

# def 세일_입력(request):
#     print(request.POST)
#     context = {
#         "폼키":SalesForm
#     }
#     return render(request, "newfolder/세일_입력.html", context)

# def 세일_입력(request):     # 형석쌤 인프런, Form
#     print(request.POST)
#     if request.method == "POST":
#         if SalesForm(request.POST).is_valid():
#             이름 = request.POST.get("first_name")
#             성 = request.POST.get("last_name")
#             나이 = request.POST.get("age")
#             new_sale = Sale()
#             new_sale.first_name = 이름
#             new_sale.last_name = 성
#             new_sale.age = 나이
#             new_sale.person =  Person.objects.first()
#             new_sale.save()
#             return redirect("/세일목록")
#     return render(request, "newfolder/세일_입력.html", context={"폼키":SalesForm})

# def 세일_입력(request):  # 기초부터 제작하는 장고, Form
#     print(request.POST)  # 객체
#     폼 = SalesForm()
#     if request.method == "POST":
#         print("포스트 메소드로 왔네요")
#         폼 = SalesForm(request.POST)
#         if 폼.is_valid():
#             print("유효하네요")
#             print(폼.cleaned_data)
#             이름 = 폼.cleaned_data['first_name']
#             성 = 폼.cleaned_data['last_name']
#             나이 = 폼.cleaned_data['age']
#             사람 =  Person.objects.first()
#             Sale.objects.create(
#                 first_name = 이름,
#                 last_name = 성,
#                 age = 나이,
#                 person = 사람
#             )
#             print("세일이 입력되었습니다")
#             return redirect("/세일목록")
#     context = {
#         "폼키": 폼
#     }
#     return render(request, "newfolder/세일_입력.html", context)

def 세일_업데이트(request, pk):        # 모델폼
    사람 = Sale.objects.get(id=pk)
    # 폼 = SaleModelForm()
    폼 = SaleModelForm(instance=사람) 
    if request.method == "POST":
        폼 = SaleModelForm(request.POST, instance=사람)
        if 폼.is_valid():
            폼.save()
            return redirect("/세일목록")
    context = {
            "사람키":사람,
            "폼키": 폼
    }
    return render(request, "newfolder/세일_업데이트.html", context)

def 세일_지우기(request, pk):
    사람 = Sale.objects.get(id=pk)
    사람.delete()
    return redirect("/세일목록")

# class 세일_지우기(DeleteView):
#     model = Sale
#     context_object_name = '사람키'
#     success_url = reverse_lazy('세일목록1:delete')
#     template_name = 'sales/세일상세.html'

# def 세일_업데이트(request, pk):        # 일반폼
#     사람 = Sale.objects.get(id=pk)
#     폼 = SalesForm()
#     if request.method == "POST":
#         폼 = SalesForm(request.POST)
#         if 폼.is_valid():
#             이름 = 폼.cleaned_data['first_name']
#             성 = 폼.cleaned_data['last_name']
#             나이 = 폼.cleaned_data['age']
#             사람.frist_name = 이름
#             사람.last_name = 성
#             사람.age = 나이
#             사람.save()
#             return redirect("/세일목록")
#     context = {
#         "사람키": 사람,
#         "폼키":폼
#         }
#     return render(request, "newfolder/세일_업데이트.html", context)



def 홈페이지(request):
    드실분 = 아이디.objects.all()
    # return HttpResponse("응 나야")
    # return render(request, "newfolder/아무거나1.html")
    context = {'메뉴': '짜장',
               '가격': 6000,
               '예산': '5000원',
               '손님들': 드실분,
               }
    return render(request, "아무거나2.html", context)

# class SalesCreateView(CreateView):
#     model = Sale
#     template_name = 'newfolder/아무거나1.html'
#     # success_url = reverse_lazy()
#     def etc(request):
#         context = {'메뉴':'짜장',
#             '가격':6000,
#             '예산':'5000원',
#             }
#         return render(request, "newfolder/아무거나1.html", context)

sales/templates/newfolder/세일_업데이트.html
{% extends 'base.html' %}
{% block content %}

<a href="{% url '홈페이지:목록' %}">세일목록</a>
<a href="{% url '세일목록1:목록' %}">세일목록</a>
    <p>{{ 사람키.last_name }}{{ 사람키.first_name }}님의 개인 정보를 수정해주세요.</p>
    <form method="post">
    {% csrf_token %}
    {{ 폼키.as_p }}
    <button type="submit">전송</button>
    </form>

{% endblock  %}

sales/templates/newfolder/세일_입력.html
{% extends 'base.html' %}
{% block content %}

    <p>세일을 입력해주세요.</p>
    <form method="post">
    {% csrf_token %}
    {{ 폼키.as_p }}
    <button type="submit">전송</button>
    </form>

{% endblock  %}

sales/templates/newfolder/세일목록.html
{% extends 'base.html' %}
{% block content %}

<a href="/세일목록/make/">세일 만들기</a>
<a href="{% url '세일목록1:생성' %}">세일 만들기</a>
<a href="{% url '홈페이지:생성' %}">세일 만들기</a>

<h1>이것이 세일 목록들 입니다.</h1>
{% for 인간 in 사람키 %}
    <div class="세일">
        <a href="/세일목록/{{인간.pk}}">{{ 인간.last_name }} {{ 인간.first_name }} </a> 나이는 {{ 인간.age }}
        <a href="{% url '세일목록1:상세' 인간.pk %}">{{ 인간.last_name }} {{ 인간.first_name }} </a> 나이는 {{ 인간.age }}
        <a href="{% url '홈페이지:상세' 인간.pk %}">{{ 인간.last_name }} {{ 인간.first_name }} </a> 나이는 {{ 인간.age }}
    </div>
{% endfor %}

<!-- <br>
사람.frist : {{ 사람first }}
<br>
사람.frist.frist_name : {{ 사람first.first_name }} -->

{% endblock  %}

sales/templates/newfolder/세일상세.html
{% extends 'base.html' %}
{% block content %}

<a href="{% url '홈페이지:목록' %}">세일목록</a>
<a href="{% url '세일목록1:목록' %}">세일목록</a>
<h1>이것이 고객 {{ 사람키.first_name }}님의 나이 정보입니다.</h1>
    <p>이 분의 나이는 {{ 사람키.age }}입니다.</p>
    <p>영업 실적을 올린 직원은 {{ 사람키.person }}입니다.</p>
    {{ 사람키 }}
    <!-- <p><a href="./update">업데이트</a></p>
    <p><a href="./delete">삭제</a></p> -->
    <p><a href="/세일목록/{{ 사람키.pk }}/update">업데이트</a>
    <a href="{% url '세일목록1:업뎃' 사람키.pk %}">업데이트</a>
    <a href="{% url '홈페이지:업뎃' 사람키.pk %}">업데이트</a></p>
    <p><a href="/세일목록/{{ 사람키.pk }}/delete">삭제</a>
    <a href="{% url '세일목록1:지우기' 사람키.pk %}">삭제</a>
    <a href="{% url '홈페이지:지우기' 사람키.pk %}">삭제</a></p>

{% endblock  %}

templates/base.html
<html>
<head>
<title> 타이틀 넣어주세요 </title>
{# bootstrap #}
<!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->
{# tailwind #}
<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

</head>

<body>
<div class="max-w-7xl mx-auto bg-purple-300 bg-opacity-75">
{% block content %}

{% endblock  %}
</div>
{% include '프로그램.html' %}
    
</body>

</html>

templates/아무거나2.html
<h1>아무거나 먹자</h1>
점심<p>
{{ 메뉴 }} : {{ 가격 }}원 <p>
예산 : {{ 예산 }}<p>
밥 먹는 사람들 : {{ 손님들 }}
<p>
드시는 분
<ul>
{% for 손님 in 손님들 %}
<li>{{ 손님 }}</li>
{% endfor %}
</ul>
</p>

templates/프로그램.html
<script>
    console.log("안녕")
</script>